### ISSUE TITLE
registerTable problem

### ISSUE THREAD

**Issue by zell147258** [memsql/memsql-spark-connector#11]
I have a MemSQL cluster. I tried connect to it and read some data from a Table but when I select my table the program throw this exception:
```
Exception in thread "main" org.apache.spark.sql.AnalysisException: Table not found: Clienti;
	at org.apache.spark.sql.catalyst.analysis.package$AnalysisErrorAt.failAnalysis(package.scala:42)
	at org.apache.spark.sql.catalyst.analysis.Analyzer$ResolveRelations$.getTable(Analyzer.scala:306)
```

I tried different ways to do this: 
```
object LoadTestSpark extends App {
  val conf = new SparkConf().setAppName("MemSQL Example")
  conf.set("memsql.host", "192.168.3.12")
  conf.setMaster("local[1]")
  val sparkContext = new SparkContext(conf)
  val memsqlContext = new MemSQLContext(sparkContext)
  memsqlContext.setDatabase("MyDB")
memsqlContext.sql("select * from Client").registerTempTable("client")
}
```

```
object LoadTestSpark extends App {
  val conf = new SparkConf().setAppName("MemSQL Example")
  conf.set("memsql.host", "192.168.3.12")
  conf.setMaster("local[1]")
  val sparkContext = new SparkContext(conf)
  val memsqlContext = new MemSQLContext(sparkContext)
  memsqlContext.setDatabase("MyDB")
  val client = memsqlContext.table("Client")
}
```

but in both cases it does not work.

If i run this: 
```
...
memsqlContext.tableNames().foreach(println)
...
```
the output is:
```
...
`MyDB`.`Checkup_dati`
`MyDB`.`Chiamate_blocchi`
`MyDB`.`Cicli`
`MyDB`.`Classificazioni`
`MyDB`.`Client`
....

what can I do for load data from my tables?

**Comment by carlsverre** [comment]
Hi Zell, I am curious about the error that was raised, namely `Table not found: Clienti`.  Notice the `i` at the end of the table name?  Can you verify that you didn't try selecting from `Clienti` when you meant to select from `Client`?

Once you have verified that can you try running `memsqlContext.table("MyDB.Client")` and see if that gives you back the table reference you want?

**Comment by zell147258** [comment]
Hi Carl, 
I renamed DB name and table name from Italian to English for write this issue. 
In my tests all names were correct.

If I try:
```
memsqlContext.table("MyDB.Client")
```
the result is: 
```
org.apache.spark.sql.AnalysisException: Specifying database name or other qualifiers are not allowed for temporary tables. If the table name has dots (.) in it, please quote the table name with backticks (`).;
```
and this error also happens if I try
```
memsqlContext.table(memsqlContext.tableNames().head)
```
and 
```
memsqlContext.table("`MyDB`.`Client`")
```

**Comment by carlsverre** [comment]
I appreciate you checking on that.  Just wanted to rule out the base case first.  :)

Today I tried to reproduce your issue, and was unable to.  I also notice that in my version of Spark/Connector running something like `memsqlContext.table("MyDB.Client")` works as expected.  It sounds like you are running a different version of something than I.

My version of Spark is: 1.5.1
My version of the Connector is: 1.2.1

Can you check on your versions?  Also if possible can you use the MemSQL Spark Distribution which has been certified to work with the latest version of the connector?  You can get the MemSQL Spark Distribution from here: http://versions.memsql.com/memsql-spark/latest

Thanks

**Comment by zell147258** [comment]
Ok, I was using spark 1.6.0. 
Now I have downgrade at 1.5.1 and it work correctly. 
Maybe It's a good idea to add this info in Readme.
Thanks a lot!

**Comment by carlsverre** [comment]
Awesome to hear the issue has been resolved.  You are completely right - we don't have good dependency documentation in this project.  I will update the readme to reflect that.  Thank you.

**Comment by pmuthal** [comment]
I got the same issue. I don't want to downgrade the spark version . Is there any way i can use with spark 1.6 ?

**Comment by choochootrain** [comment]
@pmuthal this project is compiled against spark 1.5.2 - see #24 for more context on the roadmap
