### ISSUE TITLE
Support pushdown for RIGHT OUTER JOINS

### ISSUE THREAD

**Issue by chandransuraj** [memsql/memsql-spark-connector#14]
Right now we support pushdown to memsql for left outer joins only. It would be great if we have pushdown support for other join operations as well.

**Comment by carlsverre** [comment]
We are looking at building this feature soon - thank you for filing the issue so we can track it more easily. Will update when we make progress on this.

**Comment by chandransuraj** [comment]
Great to hear. Thanks. I was working on a patch for right outer join but; more test cases would be awesome.

**Comment by carlsverre** [comment]
Oh sweet - please contribute pull reqs if you have it working.  Even just one more join would be great.  :)

**Comment by carlsverre** [comment]
Unfortunately with our move to Spark 2.0 we removed our extensive SQL pushdown integration until it is formally supported by Spark.
