### ISSUE TITLE
ReceiverInputDStream in MemSQL Streamliner

### ISSUE THREAD

**Issue by ecesena** [memsql/memsql-spark-connector#16]
Have you ever investigated if a `ReceiverInputDStream` can work with MemSQL Streamliner like a "normal" `InputDStream` does?

I was trying to create a KafkaExtractor based on:
https://github.com/dibbhatt/kafka-spark-consumer
(mostly to get checkpointing to Zookeeper for free)

My code is very similar to the KafkaExtractor/ByteArrayExtractor, but fails with:
```
org.apache.spark.SparkException: org.apache.spark.streaming.dstream.PluggableInputDStream@2b57a5f5 has not been initialized
```
I tried running `start()` on the `ReceiverInputDStream`, running `onStart()` on its receiver, etc., but no luck.

I guess `SparkStreamingContext.start()` is doing a lot of stuff to make `ReceiverInputDStream`s work... I was wondering if you ever had experience with that.

**Comment by choochootrain** [comment]
i haven't been able to wrestle those things into working without the `StreamingContext`. note that we [modify the `KafkaExtractor`](https://github.com/memsql/memsql-spark-connector/blob/master/interface/src/main/scala/org/apache/spark/streaming/kafka/MemSQLDirectKafkaInputDStream.scala#L50) to avoid this problem so you might have to modify `PluggableInputDStream` as well.

alternatively, the interface now supports checkpointing in the [api](http://memsql.github.io/memsql-spark-connector/latest/api/#com.memsql.spark.etl.api.Extractor)
and there is an [example kafka extractor](https://github.com/memsql/streamliner-examples/blob/master/kafka/src/main/scala/CheckpointingKafkaExtractor.scala) which has checkpointing enabled.

**Comment by ecesena** [comment]
++

Thanks for the pointers, I was looking at the new checkpointing feature, it looks great.
