### ISSUE TITLE
Spark MemSQL Connector looses connection after idle time

### ISSUE THREAD

**Issue by mauropirrone** [memsql/memsql-spark-connector#21]
Example:

val df = memsqlContext.read.format("com.memsql.spark.connector").load("db.table")

5 minutes idle time...

val df = memsqlContext.read.format("com.memsql.spark.connector").load("db.table") ...fails

Doing the same using the standard spark jdbc dataframe api, it works.

**Comment by carlsverre** [comment]
No longer an issue since we removed the connection pooling part of the code in the 3.0.0-beta
