### ISSUE TITLE
load data in upsert mode

### ISSUE THREAD

**Issue by Liorba** [memsql/memsql-spark-connector#26]
when looking in the code [here](https://github.com/memsql/memsql-spark-connector/blob/master/connectorLib/src/main/scala/org/apache/spark/sql/memsql/SparkImplicits.scala#L49)

I saw that upsert mode is not supported yet.
is there a plan to support sometime?

Thanks

**Comment by choochootrain** [comment]
normally we use `LOAD DATA` for ingesting into MemSQL, but if you specify an `ON DUPLICATE KEY UPDATE` clause we fall back to using inserts. do you need this to be a `LOAD DATA` query for some reason? functionally it will do the right thing, just using batched insert statements.

**Comment by Liorba** [comment]
can you share an example of an  upsert ingestion with spark connector

**Comment by choochootrain** [comment]
```
import com.memsql.spark.connector.sql.{TableIdentifier, SaveTomemSQLConf}

val conf = SaveToMemSQLConf(..., saveMode = SaveMode.Overwrite, ...)
df.saveToMemSQL(TableIdentifier("db", "t"), conf)
```

see
http://memsql.github.io/memsql-spark-connector/latest/api/#com.memsql.spark.connector.sql.TableIdentifier

http://memsql.github.io/memsql-spark-connector/latest/api/#org.apache.spark.sql.memsql.SaveToMemSQLConf

http://memsql.github.io/memsql-spark-connector/latest/api/#com.memsql.spark.connector.package$$DataFrameFunctions
