### ISSUE TITLE
update only mode

### ISSUE THREAD

**Issue by Liorba** [memsql/memsql-spark-connector#28]
Hey,
is there an option to only update a table ? with data coming from a stream
in saveToMemSql there are 2 available strategies :
1. insert
2. load

Thanks,
Lior

**Comment by choochootrain** [comment]
The ingest strategies are the implementations that allow us to get data into MemSQL. They do not control INSERT/REPLACE/UPDATE/RAISE semantics so they are irrelevant here.

See `saveMode` in [SaveToMemSQLConf](http://memsql.github.io/memsql-spark-connector/latest/api/#org.apache.spark.sql.memsql.SaveToMemSQLConf). 
Here are the semantics for the different save modes: http://spark.apache.org/docs/1.5.2/sql-programming-guide.html#save-modes

For updates you could do something like
```scala
val df = createDataFrameFromSomeOtherCode()
df.saveToMemSQL(TableIdentifier("db", "table"), SaveToMemSQLConf(saveMode=SaveMode.Overwrite, ...))
```

**Comment by Liorba** [comment]
this solution result in replace syntax, which is does not allow me to update specific cell in the table
i.e:
I have a table with user_id,name,balance
and I want to update only the balance which I can get from a stream for example(having only user_id and balance fields).
the generated replace statement would result in something like :

"REPLACE INTO TABLE tbl(user_id,balance) values(1234,300.00),(456,456.00)"
this would result in erasing the name field..

**Comment by choochootrain** [comment]
`saveToMemSQL` is designed to write the contents of a `DataFrame` to a table in MemSQL, matching the schema between the two.

Single column updates that you're doing would have a different schema (missing values for other columns) and so would not be possible with this api. You could feasibly do something like
```scala
df.foreach { updateRow =>
  runJDBCQuery("UPDATE table SET ${updateRow.col}=${updateRow.value}")
}
```
