### ISSUE TITLE
Action.c(5): Error -27791: Server "10.10.61.193" has shut down the connection prematurely

### ISSUE THREAD

**Issue by Supanccy** [memsql/memsql-spark-connector#3]
Hi,when I use loadrunner test job server for 1000 concurrency vuser.  The job server occur error, such as:
Action.c(5): Error -27791: Server "10.10.61.193" has shut down the connection prematurely

Note when I use  500concurrency vuser ther job server work well。

this problem Bothering me for a long time,  can you help me ,thanks.

**Comment by wsong** [comment]
Hey,

Are you using HP LoadRunner?  How are you doing so with this code?  This repo is a library for using MemSQL with Apache Spark, so are you running HP LoadRunner against an application that you built with this code?

**Comment by choochootrain** [comment]
closing for now - this can be re-opened if you're still seeing this issue
