### ISSUE TITLE
MemSQLConnectionPool connect(info: MemSQLConnectionInfo) always invokes a connection

### ISSUE THREAD

**Issue by ram-copart** [memsql/memsql-spark-connector#32]
In testing I see the connect() always invokes a connection since it is not properly checking on the key but does not add it to the pool since there is a check pools.putIfAbsent()

In MemSQLConnectionPool.scala
  def connect(info: MemSQLConnectionInfo): Connection = {
    if (!pools.contains(info)) {

should be changed to 

  def connect(info: MemSQLConnectionInfo): Connection = {
    if (!pools.containsKey(info)) {
Let me know if you want me to submit a PR, thanks.

**Comment by lucyyu** [comment]
Good find -- thank you! It's been fixed.
