### ISSUE TITLE
Single RDD partition

### ISSUE THREAD

**Issue by ronassa** [memsql/memsql-spark-connector#33]
although I'm configuring database name when loading I'm keeping getting single RDD partition 
`ss.read.format("com.memsql.spark.connector").options(Map("path" -> ("table"),"database" -> ("metrics"))).load()`

db is configured with 32 partitions:
`memsql> show partitions on metrics;
+---------+----------------+------+--------+--------+
| Ordinal | Host           | Port | Role   | Locked |
+---------+----------------+------+--------+--------+
|       0 | 10.125.134.164 | 3307 | Master |      0 |
|       1 | 10.125.134.164 | 3307 | Master |      0 |
|       2 | 10.125.134.164 | 3307 | Master |      0 |
|       3 | 10.125.134.164 | 3307 | Master |      0 |
|       4 | 10.125.134.164 | 3307 | Master |      0 |
|       5 | 10.125.134.164 | 3307 | Master |      0 |
|       6 | 10.125.134.164 | 3307 | Master |      0 |
|       7 | 10.125.134.164 | 3307 | Master |      0 |
|       8 | 10.125.134.164 | 3307 | Master |      0 |
|       9 | 10.125.134.164 | 3307 | Master |      0 |
|      10 | 10.125.134.164 | 3307 | Master |      0 |
|      11 | 10.125.134.164 | 3307 | Master |      0 |
|      12 | 10.125.134.164 | 3307 | Master |      0 |
|      13 | 10.125.134.164 | 3307 | Master |      0 |
|      14 | 10.125.134.164 | 3307 | Master |      0 |
|      15 | 10.125.134.164 | 3307 | Master |      0 |
|      16 | 10.125.134.164 | 3307 | Master |      0 |
|      17 | 10.125.134.164 | 3307 | Master |      0 |
|      18 | 10.125.134.164 | 3307 | Master |      0 |
|      19 | 10.125.134.164 | 3307 | Master |      0 |
|      20 | 10.125.134.164 | 3307 | Master |      0 |
|      21 | 10.125.134.164 | 3307 | Master |      0 |
|      22 | 10.125.134.164 | 3307 | Master |      0 |
|      23 | 10.125.134.164 | 3307 | Master |      0 |
|      24 | 10.125.134.164 | 3307 | Master |      0 |
|      25 | 10.125.134.164 | 3307 | Master |      0 |
|      26 | 10.125.134.164 | 3307 | Master |      0 |
|      27 | 10.125.134.164 | 3307 | Master |      0 |
|      28 | 10.125.134.164 | 3307 | Master |      0 |
|      29 | 10.125.134.164 | 3307 | Master |      0 |
|      30 | 10.125.134.164 | 3307 | Master |      0 |
|      31 | 10.125.134.164 | 3307 | Master |      0 |
+---------+----------------+------+--------+--------+
32 rows in set (0.00 sec)
`

**Comment by lucyyu** [comment]
What if you try 
ss.read.format("com.memsql.spark.connector").options(Map("path" -> ("metrics.table"))).load()
?

Sorry if this is not clear in the documentation, but the "database" option is currently meant to be used with the "query" option. If you have specified a "path", it will not look at the "database" field at all. So if you have specified a table in "path" without a database, it will default to using whatever defaultDatabase is set in your Spark configurations.

**Comment by ronassa** [comment]
Worked. thanks.
