### ISSUE TITLE
java.sql.SQLException: Communications link failure when trying to load data

### ISSUE THREAD

**Issue by alexanderzafirov** [memsql/memsql-spark-connector#39]
Hello,

I run Spark 2.2.0 on a Databricks cluster with 1 master and 1 slave. My memsql-connector version is 2.0.2.

I setup my conf
```
val memsql_host = sc.getConf.get("spark.memsql.host")
val memsql_port = sc.getConf.get("spark.memsql.port")
val memsql_user = sc.getConf.get("spark.memsql.user")
val memsql_password = sc.getConf.get("spark.memsql.password")
val memsql_defaultDatabase = sc.getConf.get("spark.memsql.defaultDatabase")
```
... and try to connect over jdbc
```
val pc_conn_str = s"jdbc:mysql://$memsql_host:$memsql_port/$memsql_defaultDatabase"
val pc_conn = DriverManager.getConnection(pc_conn_str, memsql_user, memsql_password)
val pc_stmt = pc_conn.createStatement
val pc_query ="SELECT COUNT(1) as part_count FROM INFORMATION_SCHEMA.TABLE_STATISTICS WHERE TABLE_NAME = 'job_matrix';"
val pc_rs = pc_stmt.executeQuery(pc_query);
 
var part_count = 2

while (pc_rs.next())
{
  part_count =  pc_rs.getInt("part_count")
}
pc_stmt.close()
```
... I succeed and get a result for `part_count`.

When I try to do the same with the memsql-connector
```
val tbl_job_matrix = sqlContext
  .read
  .format("com.memsql.spark.connector")
  .options(Map("query" -> ("SELECT COUNT(1) as part_count FROM INFORMATION_SCHEMA.TABLE_STATISTICS WHERE TABLE_NAME = 'job_matrix'"),
				 "database" -> "job_matrix"))
  .load()
```
... I get `java.sql.SQLException: Cannot create PoolableConnectionFactory (Communications link failure`

Clearly it's not a an access issue - which is what documentation points me to. Can you suggest a fix or something to check? Also is there a way to setup a timeout on the connection since it takes quite some time until I get the failure?

Thank you!

**Comment by lucyyu** [comment]
Do you have access to the Spark session? If you have a Spark session "sparkSession", try setting the settings "spark.memsql.host", etc on the sparkSession.conf() instead, and replace sqlContext with sparkSession in your Dataframe statement. 

In the Spark connector we look at the RuntimeConfig, which you get from sparkSession.conf(). The various confs for SparkSession, SqlContext, and SparkContext are slightly different (return different lasses even) and changes at runtime are not seen by all of them -- There's a design doc from the Spark developers with some more explanation here: https://issues.apache.org/jira/browse/SPARK-13520 .

**Comment by alexanderzafirov** [comment]
Thanks for the reply. I figured the problem was that I hadn't given access to Sparks's master and worker to the master and leaf nodes of Memsql.
