### ISSUE TITLE
zero date time behaviour connection property

### ISSUE THREAD

**Issue by dyaneshvarun** [memsql/memsql-spark-connector#42]
Getting this error while saving a dataframe with df.write

The connection property 'zeroDateTimeBehavior' acceptable values are: 'CONVERT_TO_NULL', 'EXCEPTION' or 'ROUND'. The value 'convertToNull' is not acceptable

**Comment by carlsverre** [comment]
My guess is that you are running a newer version of JDBC or org.apache.commons.dbcp2.  The version we used when testing the connector works.  That version is 2.1.1.
