### ISSUE TITLE
Scala 2.11 is not supported in Spark 3.0.0

### ISSUE THREAD

**Issue by zacikpetr** [memsql/memsql-spark-connector#43]
All 2.11 modules are useless in Spark 3, we need to support 2.12.

**Comment by carlsverre** [comment]
We are starting to invest in this project.  Currently our timeline for Scala 2.12 support is going to be after Spark 3.0 is released.  If you are a paid customer with MemSQL and have a use-case which requires us to release Spark 3.0 support during their pre-release please reach out to Support or your account manager to help set the priority of this development.  Thanks!
