### ISSUE TITLE
Question on merge functionality

### ISSUE THREAD

**Issue by samminen** [memsql/memsql-spark-connector#53]
Hello,
  In memsql-spark-connector, I see there is merge option which will happen based on primary key (PK) by using overwriteBehavior=merge option.

    In my case, I do not have any primary key for my memsql table. Is there any other way we can do merge by using memsql-spark-connector ?

I am looking for below two functionalities, when I say merge:

1. If record exists, I want to overwrite
2. If record doesn't exists, then I want insert as new record.

Based on memsql documentation, I couldn't find any help regarding this question for merge without PK.

**Comment by samminen** [comment]
Can you please help me on this question ? this is bit urgent for our work.
Thank you for all your support;

**Comment by blinov-ivan** [comment]
Currently, we don't have an option to merge records without a key, because without a primary key we can't say if such a record already exists and should be replaced with the new one.
Without a primary key, each record is a new record in the database.
