### ISSUE TITLE
load balancing for data ingestion is not working with multi aggregators

### ISSUE THREAD

**Issue by DeanJain** [memsql/memsql-spark-connector#59]
even after setting right config as per doc, the ingestion load from spark connector is only going to one aggregator only from spark connector.

config set:
spark.conf.set("spark.datasource.memsql.ddlEndpoint", "memsql-master.cluster.internal")
spark.conf.set("spark.datasource.memsql.dmlEndpoints", "memsql-master.cluster.internal,memsql-child-1.cluster.internal:3307")

ran job multiple times and all the load infile commands are going to same aggregator.

**Comment by carlsverre** [comment]
Will be fixed in the next release (should be today). Thanks for the bug report!

**Comment by carlsverre** [comment]
Commit for reference: https://github.com/memsql/memsql-spark-connector/commit/c74118dc05789d0229b2127f13a79c478effc012

**Comment by DeanJain** [comment]
Great news @carlsverre, thanks a lot for the fix, did you release this on maven ?
