### ISSUE TITLE
avro Date format exception

### ISSUE THREAD

**Issue by bolcman** [memsql/memsql-spark-connector#62]
When I switch to loadDataFormat=Avro 

I get an error when I have DataFrame with Date column 

org.apache.avro.AvroRuntimeException: Unknown datum type java.sql.Date:

thanks, 
Aleks

**Comment by AdalbertMemSQL** [comment]
Hello, Alex.

The Avro format does not support the writing of TIMESTAMP and DATE types. 
As a result, the SingleStore Spark Connector currently does not support these types with Avro serialization.
https://docs.singlestore.com/v7.1/third-party-integrations/spark-3-connector/#data-type-conversion-remarks

**Comment by blinov-ivan** [comment]
@bolcman is there anything else we could help you with?

**Comment by blinov-ivan** [comment]
@bolcman closing this issue for now - please reopen if you will need some additional help with Avro serialization.
