### ISSUE TITLE
load data to memsql table from Hadoop (HDFS) ORC files

### ISSUE THREAD

**Issue by samminen** [memsql/memsql-spark-connector#63]
Hello Team,
   I have a external HIVE table with billions of records in Hive and the underlying files are ORC format for this table. Is there a way I can use any memsql pipeline concept or any other memsql approach I can read data from HDFS ORC files and load to memsql table ?

we have memsql and hadoop on two different machine in the same network.

We tried using memsql-spark connector, but data loads very slow. Trying other options to load the data quickly.

**Comment by AdalbertMemSQL** [comment]
Hello,
It is possible to achieve pretty good performance with memsql-spark connector. 
Connector creates one LOAD DATA query per RDD partition and executes them in parallel.
Also, it is load balancing these queries between dmlEndpoints.
These two things (number of RDD partitions and aggregators in the cluster) can improve the performance.

**Comment by carlsverre** [comment]
Closing this issue for now - please reopen if you are unable to improve performance via increasing the number of partitions in the RDD you are writing to the database.  Also ensure that you have more than one aggregator listed in the `dmlEndpoints` configuration of the connector.
