### ISSUE TITLE
support for spark 3.0.x..

### ISSUE THREAD

**Issue by bolcman** [memsql/memsql-spark-connector#64]
Hi, 

any plan to support spark 3.0.x version ?

thanks, 
Aleks

**Comment by blinov-ivan** [comment]
Hi @bolcman we already support 3.0.0 version of spark in `3.1.0-beta` version of our spark-connector.
Please check [maven](https://mvnrepository.com/artifact/com.memsql/memsql-spark-connector_2.12/3.1.0-beta1-spark-3.0.0) or [spark-packages](https://spark-packages.org/package/memsql/memsql-spark-connector)

Thanks!
